name: Azure Graph API Automation
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
  schedule:
    - cron: "0 0 * * *"

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          DL_PREFIX: ${{ vars.DL_PREFIX }}
          OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
          MEMBER_EMAIL: ${{ secrets.MEMBER_EMAIL }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_THUMBPRINT: ${{ secrets.AZURE_THUMBPRINT }}
          AZURE_PRIVATE_KEY: ${{ secrets.AZURE_PRIVATE_KEY }}
        run: |
          python app.py

      - name: Save Log
        run: |
          date -u '+Date: %F Time: %H:%M:%S %Z' >> actions.log

      - name: commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email ""

          git checkout -b cronjob origin/cronjob
          git add .
          git commit -m "cronjob: run id ${{ github.run_id }}"
          git push --set-upstream origin cronjob
